version: '3.8'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    env_file:
      - .env
    networks:
      - db_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - db_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - pgadmin
    env_file:
      - .env
    networks:
      - db_network

networks:
  db_network:
    driver: bridge

