version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
