version: '3.8'

services:
  db:
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    env_file:
      - .env
    networks:
      - db_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - db_network
networks:
  db_network:
    driver: bridge

