version: '3.8'

services:
  database:
    image: postgres:13.1
    restart: always
    ports:
        - 5432:5432
    env_file:
      - .env
    networks:
      - database_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
       - ./database/data.sql:/docker-entrypoint-initdb.d/data.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - database_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      database :
        condition: service_healthy
    env_file:
      - .env
    networks:
      - database_network

networks:
  database_network:
    driver: bridge

