"""first migration

Revision ID: 84be3ab15899
Revises: 
Create Date: 2023-07-02 04:37:29.839967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84be3ab15899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_unique_constraint(None, 'cars', ['maker'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='unique')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    # ### end Alembic commands ###
